attendance/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.cache import never_cache


app_name = 'attendance'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', never_cache(views.login_user), name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('home', views.home, name='home'),
    path('add/<int:subject>/<int:where>', views.add, name='add'),
]

attendance_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendance.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

attendance/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
import os
from django.dispatch import receiver


# belongs_to, where refer to the class eg. SE COMP, BE COMP

class Class(models.Model):
    name = models.CharField(max_length=100)
    strength = models.IntegerField()

    def __str__(self):
        return self.name


class Student(models.Model):
    uid = models.IntegerField()
    roll = models.IntegerField()
    name = models.CharField(max_length=100)
    address = models.TextField()
    belongs_to = models.ForeignKey(Class, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Subject(models.Model):
    where = models.ManyToManyField(Class)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Faculty(AbstractUser):
    subject = models.ManyToManyField(Subject)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Lecture(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    where = models.ForeignKey(Class, on_delete=models.CASCADE)
    student = models.ManyToManyField(Student)
    date = models.DateField()
    time_from = models.IntegerField()
    time_to = models.IntegerField()

    def __str__(self):
        return str(self.subject) + " " + str(self.where) + "|" + str(self.date) + "|" + str(self.time_from) + "-" + str(self.time_to)

attendance/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *


class UserForm(UserCreationForm):
    class Meta:
        model = Faculty
        fields = ('username', 'first_name', 'last_name', 'password')


class EditProfileForm(UserChangeForm):
    class Meta:
        model = Faculty
        fields = ('username', 'first_name', 'last_name', 'subject')


"""class EditStudentProfileForm(UserChangeForm):
    

    class Meta:
        model = Student
        fields = ('phone_number', 'qualification', 'current_city', 'photo', 'resume', 'address')"""

attendance/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from .models import *
import datetime


def index(request):
    return render(request, 'attendance/index.html')


def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('attendance:home')
            else:
                return render(request, 'attendance/login.html', {'error_message': 'Your account is not active.'})
        else:
            return render(request, 'attendance/login.html', {'error_message': 'Invalid login'})
    return render(request, 'attendance/login.html')


def logout_user(request):
    logout(request)
    return redirect('attendance:login_user')


def home(request):
    if not request.user.is_authenticated:
        return redirect('attendance:login_user')

    get_defaulters(request)
    subjects = request.user.subject.all().values()

    for subject in subjects:
        subject['where'] = request.user.subject.where.all().values()

    return render(request, 'attendance/home.html', {'subjects': subjects})


def add(request, subject, where):
    if request.method == "POST":
        lecture = Lecture()
        lecture.faculty = request.user
        lecture.subject = get_object_or_404(Subject, pk=subject)
        lecture.where = get_object_or_404(Class, pk=where)
        lecture.date = datetime.datetime.strptime(request.POST.get("date"), "%Y-%m-%d").date()
        lecture.time_from = int(request.POST.get("time_from"))
        lecture.time_to = int(request.POST.get("time_to"))

        attendance = request.POST.get("attendance")
        attendance = list(map(int, attendance.split(',')))
        excluded = request.POST.get("excluded")
        lecture.save()

        if not excluded:
            all = Student.objects.all()
            attendance_excluded = list()
            for a in all:
                if a.roll not in attendance:
                    attendance_excluded.append(a.roll)

            student = get_list_or_404(Student, roll__in=attendance_excluded)
        else:
            student = get_list_or_404(Student, roll__in=attendance)

        print(student)
        for s in student:
            lecture.student.add(s)
        lecture.save()
        return redirect('attendance:home')

    return render(request, "attendance/add.html")


def get_defaulters(request):
    classes = Class.objects.all()
    attendance = []
    students = {}

    for clas in classes:
        temp1 = [0] * clas.strength
        temp2 = {}
        for subject in clas.subject_set.all():
            temp2[subject.pk] = temp1[:]

        students[clas.pk] = temp2.copy()

    for clas in classes:
        for subject in clas.subject_set.all():
            attendance.append(Lecture.objects.filter(where__name=clas.name, subject__exact=subject))

    for att in attendance:
        lec_count = len(att)
        for query in att:
            for student in query.student.all():
                students[query.where.pk][query.subject.pk][student.roll - 1] += 1

    print(students)

attendance/templates/attendance/add.html
{% extends 'attendance/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

    <div class="container p-5">
        <div class="card mt-5 col-12 col-md-6 mx-auto">
            <div class="card-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="date" class="control-label">Date:</label>
                        <input class="form-control" id="date" name="date" type="date" required>
                    </div>
                    <div class="form-group">
                        <label for="time_from" class="control-label">From:</label>
                        <input class="form-control" id="time_from" name="time_from" type="number" required>
                    </div>
                    <div class="form-group">
                        <label for="time_to" class="control-label">To:</label>
                        <input class="form-control" id="time_to" name="time_to" type="number" required>
                    </div>
                    <div class="form-group">
                        <label for="attendance" class="control-label">Attendance:</label>
                        <input class="form-control" id="attendance" name="attendance" type="text" required>
                    </div>
                    <div class="form-group">
                        <label for="excluded" class="control-label">Present?</label>
                        <input class="" id="excluded" name="excluded" type="checkbox">
                    </div>

                    {% if error_message %}
                        <p class="text-danger">{{ error_message }}</p>
                    {% endif %}

                    <div class="form-group">
                        <button class="btn btn-primary btn-block mt-2" type="submit">
                            Add
                        </button>
                    </div>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

attendance/templates/attendance/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SPIT{% endblock %}</title>

    <!-- Font Awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- In-app css -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <!--Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <!-- Wow.js-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css ">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js" type="text/javascript"></script>

</head>
<body>

{% block nav %}
    <!--nav-->
    <nav class="navbar navbar-expand-lg bg-primary navbar-dark fixed-top">
        <div class="container">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">Logo</a>
            <!--Toggler-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <!-- Links -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'attendance:home' %}">Home</a>
                    </li>
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'attendance:logout_user' %}">Logout</a>
                        {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Login/Sign Up
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{% url 'attendance:login_user' %}">Login</a>
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block body %}
{% endblock %}

</body>
</html>

attendance/templates/attendance/home.html
{% extends 'attendance/base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
    <div class="container mt-5 p-5">
        <div class="row">
            <div class="col col-lg-12">
                <div class="row p-4">
                    {% for subject in subjects %}
                        <div class="card mt-5 col-12 col-lg-6 col-xl-4 p-4">
                            <div class="card-body">
                                <a class="btn btn-primary" data-toggle="collapse{{ subject.pk }}"
                                   href="#collapseExample{{ subject.pk }}" role="button"
                                   aria-expanded="false" aria-controls="collapseExample{{ subject.pk }}">
                                    {{ subject }}
                                </a>
                                <div class="collapse{{ subject.pk }}" id="collapseExample{{ subject.pk }}">
                                    <div class="card card-body">
                                        <ul>
                                            {% for class in subject.where %}
                                                <li>
                                                    <a href="">{{ class.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <hr>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

attendance/templates/attendance/index.html
<h1>Test</h1>

attendance/templates/attendance/login.html
{% extends 'attendance/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}

    <div class="container p-5">
        <div class="card mt-5 col-12 col-md-6 mx-auto">
            <div class="card-body">
                <form class="form-horizontal" enctype="multipart/form-data" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="control-label">Username:</label>
                        <input class="form-control" id="username" name="username" type="text" required>
                    </div>
                    <div class="form-group">
                        <label for="password" class="control-label">Password:</label>
                        <input class="form-control" id="password" name="password" type="password" required>
                    </div>
                    {% if error_message %}
                        <p class="text-danger">{{ error_message }}</p>
                    {% endif %}

                    <a class="" href="{% url 'password_reset' %}">Forgot Password?</a>

                    <div class="form-group">
                        <button class="btn btn-primary btn-block mt-2" type="submit">
                            Login
                        </button>
                    </div>
                </form>
            </div>
        </div>

    </div>

{% endblock %}